name: Ticketing_Pipeline

on: push

jobs:
    first_job:
        runs_on: ubuntu-latest
        steps:
            - name: welcome first jobs
              run: echo "my fist job fromTicketing pipeline"
            
            - name: list files
              run: ls

            - name: read files
              run: cat README.md

              
            