name: Multiple_Jobs_seq_execution

on: push

jobs:
    build_job:
      runs-on: ubuntu-latest
      steps:
        - name: Install cowsy program
          run: sudo apt-get install cowsay -y
       
        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Iam a dragon"  >> dragon.txt

        - name: sleep for 30 seconds
          run: sleep 30
    
    test_job:
      needs: build_job
      runs-on: ubuntu-latest
      steps:
        - name: sleep for 30 seconds
          run: sleep 30
    
        - name: test file exist
          run: grep -i "dragon" dragon.txt
        
    deploy_job:
      needs: test_job
      runs-on: ubuntu-latest
      steps:
        - name: Read file
          run: cat dragon.txt

        - name: Deploy the file
          run: echo Deploying.....

            # - name: list files
            #   run: ls

            # - name: read files
            #   run: cat README.md

              
            