name: Multiple_Jobs_seq_execution_Sharingfile

on: push

jobs:
    build_job:
      runs-on: ubuntu-latest
      steps:
        - name: Install cowsy program
          run: sudo apt-get install cowsay -y
       
        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Iam a dragon"  >> dragon.txt

        - name: Upload the dragon file
          uses: actions/upload-artifact@v7
          with:
            name: dragon_file
            path: dragon.txt
    
    test_job:
      needs: build_job
      runs-on: ubuntu-latest
      steps:
        - name: Download file
          uses: actions/download-artifact@v8
          with:
            name: dragon_file
            path: dragon.txt
    
        - name: test file exist
          run: grep -i "dragon" dragon.txt
        
    deploy_job:
      needs: test_job
      runs-on: ubuntu-latest
      steps:
        - name: Download file
          uses: actions/download-artifact@v8
          with:
            name: dragon_file
            path: dragon.txt

        - name: Read file
          run: cat dragon.txt

        - name: Deploy the file
          run: echo Deploying.....

            # - name: list files
            #   run: ls

            # - name: read files
            #   run: cat README.md

              
            