name: Ticketing_Pipeline

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: welcome first jobs
              run: |
                echo "my fist job fromTicketing pipeline"
                ls -ltre
                cat README.md
              

            
            # - name: list files
            #   run: ls

            # - name: read files
            #   run: cat README.md

              
            